CREATE DATABASE IF NOT EXISTS Login_Sistema;

USE Login_Sistema;

CREATE TABLE IF NOT EXISTS Usuario (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Senha VARCHAR(255) NOT NULL,
    Tempo TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);